#
# Tk Makefile for unix (this is just a relay Makefile)
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 20-Feb-1996 09:49
# Last file update: 24-Jul-1996 15:00
#

include ../config.make

libtk.a:
	(cd $(FLAVOR); $(MAKE) libtk.a)

install:
	(cd $(FLAVOR); $(MAKE) install)

install.libs:
	(cd $(FLAVOR); $(MAKE) install.libs)

clean:
	(cd $(FLAVOR); $(MAKE) clean)
	rm -f config.*




